spring:
  application:
    name: paotui
  http:
    encoding:
      charset: utf-8
      enabled: true
  datasource:
    username: root
    password: dontconnect
    url: jdbc:mysql://121.199.76.80:3306/paotui?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # ????????????
    initial-size: 5
    min-idle: 5
    max-active: 20
    # ????????????????????
    max-wait: 60000
    # ???ü????ò??????μ??????????????????????λ?????
    time-between-eviction-runs-millis: 60000
    # ??????????????????С??????????λ?????
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # ??PSCache??????????????????PSCache???С
    pool-prepared-statements: true
    # ???ü??????????filters????????????sql???????'wall'????????
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
    use-global-data-source-stat: true
    # ???connectProperties????????mergeSql???????SQL???
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


# mybatis????
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml # ?????????λ??
  configuration:
    # ?????????????????????
    map-underscore-to-camel-case: true
  type-aliases-package: com.runningman.paotui.pojo

server:
  port: 8080




# ??????????
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql